FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Use a JDK image to run the application
FROM openjdk:17-jdk-slim
WORKDIR .
COPY --from=build /app/target/your-app-name.jar /app/app.jar
EXPOSE 8089
ENTRYPOINT ["java", "-jar", "app.jar"]

